apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: siddheshbhave7/task-tracker-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
